// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmhmtggxmcixtvssxqhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtaG10Z2d4bWNpeHR2c3N4cWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTg2NjUsImV4cCI6MjA2OTE3NDY2NX0.Tcx2LH4jwHxDwbGnkTtjRL4D8kbI5RaR1pA_WpLnK8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});